# I. NumPy.

**Оцінювання даної роботи буде ураховувати якість Вашого коду та текстових відповідей. При наявності ЛИШЕ коду , робота оцінюватися НЕ БУДЕ.**  

**Оформлення текстових відповідей повинно проводитися в текстових комірках ноутбука з використанням синтаксису [LaTeX](https://en.wikibooks.org/wiki/LaTeX/Basics) для оформлення тексту та формул.**

**Роботи ідентифіковані як ІДЕНТИЧНІ одразу отримують 0 балів.**

**При реалізації завдань потрібно використовувати методи з бібліотеки numpy та pandas.**

**Рішення з циклами будуть оцінені в 0 балів.**

0. Імпортувати numpy загальноприйнятим способом.

In [2]:
import numpy as np

1. Визначити список з оцінками студента(ки) за семестр. Використовуючи його, створити одновимірний масив numpy.

In [5]:
grades = [1,3,2,4,1,2,5,4,5,4,3,3,2,4,1,1]
grades_array = np.array(grades)
print(grades_array)

[1 3 2 4 1 2 5 4 5 4 3 3 2 4 1 1]


2. Визначити список зі списками, де кожен рядок списку формально означає магазин, а кожна колонка - певний продукт (батон, яйця першої категорії, молоко та ковбаса), а елементами на пересічі є ціни на ці продукти відповідно. Використовуючи цей список, створити матрицю (двовимірний масив) numpy.

In [4]:
prices = [
    [11, 2, 20, 300],  # Магазин 1
    [12, 3, 22, 260],  # Магазин 2
    [10, 4, 24, 290],  # Магазин 3
    [10.5, 2, 25, 285]   # Магазин 4
]

prices_matrix = np.array(prices)
print(prices_matrix)

[[ 11.    2.   20.  300. ]
 [ 12.    3.   22.  260. ]
 [ 10.    4.   24.  290. ]
 [ 10.5   2.   25.  285. ]]


3. Отримайте тип даних значень з масивів завдань 2 та 3. Виведіть їх на екран.

In [6]:
print("Тип даних у масиві:", grades_array.dtype)
print("Тип даних у матриці:", prices_matrix.dtype)

Тип даних у масиві: int64
Тип даних у матриці: float64


4. Отримайте форми (кортеж з кількістю рядків та колонок) масивів завдань 2 та 3. Виведіть їх на екран.

In [7]:
print("Форма масиву:", grades_array.shape)
print("Форма матриці:", prices_matrix.shape)

Форма масиву: (16,)
Форма матриці: (4, 4)


5. Створіть одновимірний масив за допомогою спеціальної функції numpy, який би відображав динаміку стабільно зростаючого (з рівними проміжками) прибутку з продажів  за тиждень, де у перший день не було продажів, а в останній день тижня вдалося заробити 1000 грн 50 коп.

In [8]:
profit_array = np.linspace(0, 1000.5, num=7)

print("Масив прибутку за тиждень:",profit_array)

Масив прибутку за тиждень: [   0.    166.75  333.5   500.25  667.    833.75 1000.5 ]



6. Створіть два масиви. Використовуючи їх, продемонструйте відмінність вертикального та горизонтального обʼєднання масивів.

In [12]:
array1 = [1,2,3,4,5]
array2 = [9,8,7,6,5]

horizontal = np.hstack((array1, array2))
vertical = np.vstack((array1, array2)) # робить матрицю


print(horizontal)
print(vertical)

[1 2 3 4 5 9 8 7 6 5]
[[1 2 3 4 5]
 [9 8 7 6 5]]


7. Визначити функцію, яка приймає на вході масив і транспонує його. Скористайтесь методом reshape. І не забудьте почати з docstrings.

In [19]:
def transpose_array(arr):
    """
    Транспонує заданий масив.
    
    Параметри:
        Вхідний масив для транспонування.
    
    Повертає:
        Транспонований масив.
    """
    return arr.transpose()


arr = np.array([[1,2,3,4,5],[9,8,7,6,5]])
trans = transpose_array(arr)
print(trans)

[[1 9]
 [2 8]
 [3 7]
 [4 6]
 [5 5]]


8. Створіть два масиви. Використовучи ці масиви, продемонструйте 1) операцію по-елементного додавання, 2) операцію по-елементного віднімання, 3) множення масиву на число, 4) операцію по-елементного множення, і 5) матричного множення.

In [22]:
array1 = [1,2,3,4,5]
array2 = [9,8,7,6,5]
add = np.add(array1, array2)
subtract = np.subtract(array1, array2)
multiply = np.multiply(array1, array2)
divide = np.divide(array1, array2)
print(add,subtract,multiply,divide)

[10 10 10 10 10] [-8 -6 -4 -2  0] [ 9 16 21 24 25] [0.11111111 0.25       0.42857143 0.66666667 1.        ]


9. Створіть двовимірний масив (матрицю) та розрахуйте: 1) мінімальне число, 2) максимальне число, 3) суму чисел, 4) мінімальні числа для кожного рядка, 5) максимальні числа для кожного стовпчика.

In [28]:
matrix = [
    [0,1,2,3,4],
    [10,11,12,13,14]
]
arr = np.array(matrix)
min_value = arr.min()
max_value = arr.max()
sum_value = arr.sum()
min_per_row = arr.min(axis=1)        # Мінімальні числа для кожного рядка = 1
max_per_column = arr.max(axis=0)     # Максимальні числа для кожного стовпчика = 0

print(min_value)
print(max_value)
print(sum_value)
print(min_per_row)
print(max_per_column)

0
14
70
[ 0 10]
[10 11 12 13 14]


10. Створіть матрицю , де деякі елементи повторюються. Знайдіть унікальні значення елементів цієї матриці та їхні частоти.

In [30]:
matrix = [
    [0,2,3,5,6],
    [0,5,4,8,9]
]
arr = np.array(matrix)
unique_values = np.unique(arr)
unique_values, counts = np.unique(arr, return_counts=True)

print(unique_values)
print(counts)


[0 2 3 4 5 6 8 9]
[2 1 1 1 2 1 1 1]


# II. Importing. Creating DF

0. Імпортувати бібліотеку pandas

In [9]:
import pandas as pd

11. Створити тестовий датафрейм зі списку, що містить записи пацієнтів про їхні прізвища, імена, дату народження, масу тіла та наявність медичного страхування. Одне зі значень зробить пустим. Ознайомтесь з типом кожної колонки.

In [10]:
data = [
    {"Прізвище": "Сухай", "Ім'я": "Роман", "Дата народження": "27-02-2001", "Маса тіла": 90, "Медичне страхування": True},
    {"Прізвище": "Фельдченко", "Ім'я": "Оксана", "Дата народження": "10-07-1985", "Маса тіла": 65, "Медичне страхування": False},
    {"Прізвище": "Бучко", "Ім'я": "Петро", "Дата народження": None, "Маса тіла": 56, "Медичне страхування": True},
    {"Прізвище": "Коваль", "Ім'я": "Ольга", "Дата народження": "05-03-1995", "Маса тіла": 55, "Медичне страхування": True},
]

df = pd.DataFrame(data)
print(df)
print("Типи даних у колонках:")
print(df.dtypes)

     Прізвище    Ім'я Дата народження  Маса тіла  Медичне страхування
0       Сухай   Роман      27-02-2001         90                 True
1  Фельдченко  Оксана      10-07-1985         65                False
2       Бучко   Петро            None         56                 True
3      Коваль   Ольга      05-03-1995         55                 True
Типи даних у колонках:
Прізвище               object
Ім'я                   object
Дата народження        object
Маса тіла               int64
Медичне страхування      bool
dtype: object


# III. Reading from file

12. Завантажити файл missile_attacks_daily.csv з [Kaggle](https://www.kaggle.com/datasets/piterfm/massive-missile-attacks-on-ukraine?select=missile_attacks_daily.csv). Ознайомитись з описом датасету. Додати файл до папки поточної сесії colab notebook на панелі ліворуч або на гугл диск (локально до проєкту, якщо працюєте у пайчармі). Зчитати датафрейм з файлу та вивести датафрейм на екран. Зверніть увагу на те, щоб всі колонки відповідали наведеним у описі типам даних.

In [11]:
file_path = "missile_attacks_daily.csv" 
data =pd.read_csv(file_path)

print(data)


            time_start          time_end               model  \
0     2025-01-18 20:00  2025-01-19 09:00      Shahed-136/131   
1     2025-01-17 19:00  2025-01-18 08:00      Shahed-136/131   
2     2025-01-16 19:00  2025-01-17 09:00      Shahed-136/131   
3     2025-01-16 19:00  2025-01-17 09:00    Iskander-M/KN-23   
4     2025-01-16 19:00  2025-01-17 09:00          Iskander-M   
...                ...               ...                 ...   
2039  2022-10-01 12:00  2022-10-01 12:00            Orlan-10   
2040        2022-09-30        2022-09-30            Orlan-10   
2041  2022-09-29 23:00  2022-09-29 23:59      Shahed-136/131   
2042        2022-09-28        2022-09-28                X-59   
2043        2022-09-28        2022-09-28  Reconnaissance UAV   

                                           launch_place  \
0         Bryansk oblast and Oryol oblast and Millerovo   
1     Primorsko-Akhtarsk and Bryansk oblast and Mill...   
2     Primorsko-Akhtarsk and Kursk oblast and Bryans..

# IV. Data understanding

13. Виведіть на екран перші 10 рядків зчитаного датафрейму.

In [17]:
print(data.head(10))

         time_start          time_end             model  \
0  2025-01-18 20:00  2025-01-19 09:00    Shahed-136/131   
1  2025-01-17 19:00  2025-01-18 08:00    Shahed-136/131   
2  2025-01-16 19:00  2025-01-17 09:00    Shahed-136/131   
3  2025-01-16 19:00  2025-01-17 09:00  Iskander-M/KN-23   
4  2025-01-16 19:00  2025-01-17 09:00        Iskander-M   
5  2025-01-15 20:00  2025-01-16 09:00    Shahed-136/131   
6  2025-01-15 06:00  2025-01-15 08:00         X-59/X-69   
7  2025-01-15 06:00  2025-01-15 08:00         X-22/X-32   
8  2025-01-15 06:00  2025-01-15 08:00       X-101/X-555   
9  2025-01-15 06:00  2025-01-15 08:00            Kalibr   

                                        launch_place       target  carrier  \
0      Bryansk oblast and Oryol oblast and Millerovo      Ukraine      NaN   
1  Primorsko-Akhtarsk and Bryansk oblast and Mill...      Ukraine      NaN   
2  Primorsko-Akhtarsk and Kursk oblast and Bryans...      Ukraine      NaN   
3                 Bryansk oblast and V

14. Отримайте інформацію про форму датафрейму.

In [18]:
print(data.shape)## лінії та колонки

(2044, 16)


15. Отримайте дані про кожну колонку з її назвою, типом даних та кількістю непустих значень.

In [19]:
print(data.info())
## non-null не пусті значенння

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2044 entries, 0 to 2043
Data columns (total 16 columns):
 #   Column                Non-Null Count  Dtype  
---  ------                --------------  -----  
 0   time_start            2044 non-null   object 
 1   time_end              2044 non-null   object 
 2   model                 2044 non-null   object 
 3   launch_place          1023 non-null   object 
 4   target                2016 non-null   object 
 5   carrier               225 non-null    object 
 6   launched              2041 non-null   float64
 7   destroyed             2044 non-null   int64  
 8   not_reach_goal        157 non-null    float64
 9   cross_border_belarus  32 non-null     float64
 10  back_russia           34 non-null     float64
 11  still_attacking       28 non-null     float64
 12  destroyed_details     294 non-null    object 
 13  launched_details      4 non-null      object 
 14  launch_place_details  4 non-null      object 
 15  source               

16. Отримайте статистику для колонок числового типу.

In [12]:
print("Статистика для колонок числового типу:")
print(data.describe())


Статистика для колонок числового типу:
          launched    destroyed  not_reach_goal  cross_border_belarus  \
count  2041.000000  2044.000000      157.000000             32.000000   
mean     10.609995     7.491683       20.828025              2.312500   
std      21.041038    14.190972       19.877245              2.054696   
min       1.000000     0.000000        1.000000              1.000000   
25%       1.000000     1.000000        4.000000              1.000000   
50%       2.000000     1.000000       16.000000              2.000000   
75%       9.000000     7.000000       30.000000              2.000000   
max     193.000000    99.000000      105.000000             10.000000   

       back_russia  still_attacking  
count    34.000000        28.000000  
mean      2.000000         2.821429  
std       1.154701         2.931989  
min       1.000000         1.000000  
25%       1.000000         1.000000  
50%       2.000000         1.000000  
75%       3.000000         4.000000  

17. Отримати кількість унікальних значень у кожній колонці. Вивести на екран значення та кількість цих значень у колонці, яка має найменше унікальних значень.

In [21]:
unique_counts = data.nunique()

print("Кількість унікальних значень у кожній колонці:")
print(unique_counts)

Кількість унікальних значень у кожній колонці:
time_start               864
time_end                1015
model                     61
launch_place             135
target                    97
carrier                   58
launched                 113
destroyed                 81
not_reach_goal            55
cross_border_belarus       7
back_russia                5
still_attacking            8
destroyed_details        290
launched_details           4
launch_place_details       4
source                   960
dtype: int64


In [24]:
column_with_min_unique = unique_counts.idxmin()
min_unique_count = unique_counts.min()
print(f"\nКолонка з найменшою кількістю унікальних значень: {column_with_min_unique}")
print(f"Кількість унікальних значень: {min_unique_count}")

# Унікальні значення та їхні частоти в цій колонці
unique_values = data[column_with_min_unique].value_counts()

print(f"\nЗначення та їх кількість у колонці:")
print(unique_values)


Колонка з найменшою кількістю унікальних значень: launched_details
Кількість унікальних значень: 4

Значення та їх кількість у колонці 'launched_details':
launched_details
{'X-101/X-555': 50, 'Kalibr': 12}                     1
{'X-101/X-555': 55, 'Kalibr': 24, 'Iskander-K': 7}    1
{'X-101/X-555': 57, 'Kalibr': 28}                     1
{'X-101/X-555': 77, 'Kalibr': 28, 'X-59/X-69': 10}    1
Name: count, dtype: int64


18. На основі отриманої інформації про датасет вище, опишіть по пунктах, що б ви виправили або на що б звернули увагу на кроці очищення даних і чому?

**місце для текстової відповіді**

1. Обробити пропущені дані, щоб дата сет був чистіший
2. launched_details - розпарсити її, бо виглядає як словник в словнику
3. Перевірити формат дат

...




# V. Data Cleaning

19. Перетворити колонку launched у цілочислену (Int64). Перевірити, чи все пройшло, як очікувалось.

In [27]:
# Перетворення колонки launched у цілочислену
data['launched'] = pd.to_numeric(data['launched'], errors='coerce').astype('Int64')
print("Колонка 'launched' успішно перетворена у Int64.")

# Перевірка результату
print("\nТипи даних після перетворення:")
print(data.dtypes)


print("\nПерші кілька рядків колонки 'launched':")
print(data['launched'].head())

Колонка 'launched' успішно перетворена у Int64.

Типи даних після перетворення:
time_start               object
time_end                 object
model                    object
launch_place             object
target                   object
carrier                  object
launched                  Int64
destroyed                 int64
not_reach_goal          float64
cross_border_belarus    float64
back_russia             float64
still_attacking         float64
destroyed_details        object
launched_details         object
launch_place_details     object
source                   object
dtype: object

Перші кілька рядків колонки 'launched':
0    61
1    39
2    50
3     4
4     2
Name: launched, dtype: Int64


20. Видалити колонки, де кількість непустих значень становить менше 30% від загальної кількості записів.

In [55]:
filter = 0.3 * len(data)
filtered_data = data.loc[:, data.notnull().sum() >= filter]

# Виведення результатів
print("Форма датасету до видалення колонок:", data.shape)
print("Форма датасету після видалення колонок:", filtered_data.shape)

print("\nКолонки, що залишились:")
print(filtered_data.columns)

output_file = "cleaned_data.csv"  # Назва нового файлу
filtered_data.to_csv(output_file, index=False)  # Зберігаємо без індексів



Форма датасету до видалення колонок: (434, 17)
Форма датасету після видалення колонок: (434, 9)

Колонки, що залишились:
Index(['time_start', 'time_end', 'model', 'launch_place', 'target', 'launched',
       'destroyed', 'source', 'duration'],
      dtype='object')


21. Очистити датафрейм від дублікатів (дублюючихся рядків) та записів, де атака продовжувалась відʼємну або нульову кількість часу (що фізично неможливо). Не забудьте оновити індекс. Скільки рядків було видалено? Як ви це перевірили у коді?

In [58]:
data = pd.read_csv("cleaned_data.csv")

# Початкова кількість рядків
initial_rows = data.shape[0]

# Перетворення колонок time_start і time_end у формат datetime
data['time_start'] = pd.to_datetime(data['time_start'], errors='coerce')
data['time_end'] = pd.to_datetime(data['time_end'], errors='coerce')

# Розрахунок тривалості атаки (у хвилинах)
data['duration'] = (data['time_end'] - data['time_start']).dt.total_seconds() / 60  # У хвилинах
# Видалення рядків із від'ємною або нульовою тривалістю
data = data[data['duration'] > 0]


# Оновлення індекса
data = data.reset_index(drop=True)

# Кількість рядків після очищення
final_rows = data.shape[0]

# Розрахунок кількості видалених рядків
rows_removed = initial_rows - final_rows

# Результати
print(f"Початкова кількість рядків: {initial_rows}")
print(f"Кількість рядків після очищення: {final_rows}")
print(f"Кількість видалених рядків: {rows_removed}")


Початкова кількість рядків: 434
Кількість рядків після очищення: 433
Кількість видалених рядків: 1


Видалено було 0
Проте коли я змінив в csv на неправильне значення, то видалило його


22. Виведіть на екран всі рядки, де є хоч одне пропущене значення.

In [57]:
data = pd.read_csv("cleaned_data.csv")

# Фільтрація рядків із хоча б одним пропущеним значенням
rows_with_missing_values = data[data.isnull().any(axis=1)]

# Виведення на екран
print("Рядки з пропущеними значеннями:")
print(rows_with_missing_values)


# # Знаходимо рядки без пропущених значень
# rows_without_missing_values = filtered_data[filtered_data.notnull().all(axis=1)]

# # Виведення рядків без пропущених значень
# print("Рядки без пропущених значень:")
# print(rows_without_missing_values)

# # Кількість таких рядків
# print(f"Кількість рядків без пропущених значень: {len(rows_without_missing_values)}")

Рядки з пропущеними значеннями:
              time_start             time_end                   model  \
25   2025-01-03 12:00:00  2025-01-03 20:00:00               X-59/X-69   
27   2025-01-03 12:00:00  2025-01-03 20:00:00              Iskander-M   
28   2025-01-03 12:00:00  2025-01-03 20:00:00                   C-300   
45   2024-12-25 05:00:00  2024-12-25 10:00:00  X-101/X-555 and Kalibr   
64   2024-12-14 19:00:00  2024-12-15 08:30:00                   C-300   
..                   ...                  ...                     ...   
429  2022-10-06 15:00:00  2022-10-06 20:00:00               Mohajer-6   
430  2022-10-06 09:00:00  2022-10-06 11:30:00          Shahed-136/131   
431  2022-10-06 09:00:00  2022-10-06 11:30:00               Mohajer-6   
432  2022-10-02 00:00:00  2022-10-02 02:00:00          Shahed-136/131   
433  2022-09-29 23:00:00  2022-09-29 23:59:00          Shahed-136/131   

    launch_place                            target  launched  destroyed  \
25           NaN